### ISSUE TITLE
Need some help

### ISSUE THREAD

**Issue by MoralQuestions** [alor/em-http-server#13]
How many people's lives do you think you've destroyed and do you feel responsible for the activists and other helpless people, brutally tortured and killed, who were tracked down using software you're a part of?

**Comment by NullVoxPopuli** [comment]
wat

**Comment by MoralQuestions** [comment]
@NullVoxPopuli For context, the maintainer of this project illegally accepted money from some of [these people](https://en.wikipedia.org/wiki/Hacking_Team#Customer_List), for software which was actively used to track down and silence people who tried to speak out about their government.

**Comment by NullVoxPopuli** [comment]
how do you know that?
