### ISSUE TITLE
Uninitialized variable @keep_connection_open

### ISSUE THREAD

**Issue by eqv** [alor/em-http-server#5]
```
gems/ruby-1.9.3-p194/gems/em-http-server-0.1.6/lib/em-http-server/response.rb:101: warning: instance variable @keep_connection_open not initialized
```

(If run with warnings enabled)
I do realize this is not a bug per se, but it is good style not to produce (even such pointless) warnings. Makes it harder for others to use the warnings flag to check for mistakes.

**Comment by alor** [comment]
fixed in master.  thank you.
