### ISSUE TITLE
Compare with evma_httpserver?

### ISSUE THREAD

**Issue by philayres** [alor/em-http-server#6]
I just ran across your repo of em-http-server after looking at evma_httpserver. Could you provide a few points of comparison, so I can help select the right one for my project.
- Is em-http-server a compatible replacement for evma_httpserver? 
- Can it be used to handle file uploads (if so, do you have an example?)
- Are you using the project in production?

Thanks for any feedback.

**Comment by alor** [comment]
What i didn't like about evma_httpserver was that it required a native extension to be compiled and it could give you headache if you are porting between jruby and mri. This gem is pure ruby, so no need to compile anything.
It could be used to handle file upload. It's just a simple parser for the http header, all the work must be done by your code. you just read the headers and the body of the upload and you are fine. A file upload is just a POST with a body.
yes, i'm using it in production for some different projects.

**Comment by philayres** [comment]
Thanks for the information. I appreciate your help. I will take a closer look at your project and see if it fits my needs.
