### ISSUE TITLE
Run server in non-blocking mode ?

### ISSUE THREAD

**Issue by stanimirovv** [alor/em-http-server#8]
Sorry for the noob question, but can I run the server in non blocking mode and if I can, how ?

**Comment by alor** [comment]
what exactly do you mean in non-blocking mode?  what are you trying to achive?
this gem is based on eventmachine, all the requests are already served in a non-blocking reactor.

**Comment by stanimirovv** [comment]
Consider an infinite loop. It has 2 steps - A and B. A is some function which does a bit of calculations(takes miliseconds) and B is the server. When B is not answering any requests it switches to A. When A finishes it switches to B. If B is empty it will again go to A and so on.I basically changed the EM::run from the usage to the following, with the idea that since puts is non blocking it can act as the dummy A  for a prototype.

EM::run do
    EM::start_server("0.0.0.0", 8080, HTTPHandler)
    do_work = proc{
                    puts "Hello world"
                    EM.next_tick(&do_work)
                  }
   EM.next_tick(&do_work)
end

**Comment by alor** [comment]
Is A processing inputs from B?
as it is, it works, but A and B are competing on the reactor, so if A takes time to complete, B will be blocked until A has finished.

if A and B are not dependent, why don't you use a separate thread for A?

**Comment by stanimirovv** [comment]
I had to re-install ruby and the gems. When I ran the code afterwards everything was working flawlessly. I am not sure what has caused this, but it's certain that the error isn't in the server. Thank you for taking from your time to help me and sorry for bringing up an issue which turned out to not be related to the server.
