### ISSUE TITLE
Block request 

### ISSUE THREAD

**Issue by stanimirovv** [alor/em-http-server#9]
Hello. This is another (and hopefully the last) newbie question regarding the usage of the server. 

I am trying to make the server check for a condition before answering the request. If the condition is true it will answer the request, if it will block the request and continue answering the other requests, until it eventually comes to the same request and checks for the condition again.

My attempt is to put a conditional when generating the request, however this (naive) way doesn't work - I don't get an answer from the server. I have made a gist to explain the situation better: https://gist.github.com/IamBc/ed0d9bced982e8d40499

Thanks in advance!

**Comment by alor** [comment]
what does the method get_response in your sample do?
if rand is 0, what should be the response to the client?

**Comment by stanimirovv** [comment]
Basically get_response returns some string, "Hello world" is good enough. There isn't really any need for it. I have updated the gist. https://gist.github.com/IamBc/ed0d9bced982e8d40499

Basically if it is == to zero, the response body is "Hello world". If it is different than zero, it will be blocked, moving it to the end of the queue and it will wait it's turn to be answered.(by again rolling and possibly going to the end of the loop again)

**Comment by alor** [comment]
it does not work this way, the method will return and the client will not get any response, it will not be put at the end of the queue. the callbacks are asynchronous, you cannot reorder them. each of them is handled by a different thread and unless you synchronize them with some mutex what you are trying to do it not easily feasible.

**Comment by stanimirovv** [comment]
I understand. Thank you for your time. If I make a decent solution I will post it as an example.
